# Import Packages

In [27]:
import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.stem.porter import PorterStemmer
from sklearn.model_selection import train_test_split
import regex as re
from nltk.corpus import stopwords

# Import Data

In [28]:
news = pd.read_csv("../data/news.csv", index_col = "Unnamed: 0")
world = pd.read_csv("../data/world.csv", index_col = "Unnamed: 0")

In [29]:
news.head()

,all_awardings,allow_live_comments,author,author_cakeday,author_flair_background_color,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_text_color,author_flair_type,...,subreddit_type,thumbnail,thumbnail_height,thumbnail_width,title,total_awards_received,updated_utc,url,whitelist_status,wls
0,[],False,mburbie35,NaN,NaN,NaN,[],NaN,NaN,text,...,public,default,78.0,140.0,6 injured in shooting on Philadelphia highway,0,NaN,https://edition-m.cnn.com/2019/10/13/us/philad...,all_ads,6
1,[],False,ChickenTeriyakiBoy1,NaN,NaN,NaN,[],NaN,NaN,text,...,public,default,93.0,140.0,World’s Biggest Pork Producer Warns of Bacon S...,0,NaN,https://www.bloomberg.com/news/articles/2019-1...,all_ads,6
2,[],False,Ph_Speed,NaN,NaN,NaN,[],NaN,NaN,text,...,public,default,NaN,NaN,6 injured in shooting on Philadelphia highway,0,NaN,https://www.cnn.com/2019/10/13/us/philadelphia...,all_ads,6
3,[],False,hornedviper9,NaN,NaN,NaN,[],NaN,NaN,text,...,public,default,NaN,NaN,Are We Being Played?,0,NaN,https://www.bitchute.com/video/XzeWQBcjFiQ/,all_ads,6
4,[],False,adorablewildlife,NaN,NaN,NaN,[],NaN,NaN,text,...,public,default,NaN,NaN,"Adorable Monkey Rylee Is Very Lovely, Friendly...",0,NaN,https://www.youtube.com/watch?v=9izQ3QB9uvo&am...,all_ads,6

In [30]:
world.head()

,all_awardings,allow_live_comments,author,author_cakeday,author_flair_background_color,author_flair_css_class,author_flair_richtext,author_flair_text,author_flair_text_color,author_flair_type,...,subreddit_type,thumbnail,thumbnail_height,thumbnail_width,title,total_awards_received,updated_utc,url,whitelist_status,wls
0,[],False,puppy8ed,NaN,NaN,NaN,[],NaN,NaN,text,...,public,default,73.0,140.0,Why US businesses should worry about China’s c...,0,NaN,https://www.scmp.com/news/china/article/303272...,all_ads,6
1,[],False,Davidizaverage,NaN,NaN,NaN,[],NaN,NaN,text,...,public,default,93.0,140.0,ESL chief tells staff to avoid discussing Hong...,0,NaN,https://www.pcgamer.com/esl-chief-tells-staff-...,all_ads,6
2,[],False,Davidizaverage,NaN,NaN,NaN,[],NaN,NaN,text,...,public,default,93.0,140.0,Hong Kong Police Officer Slashed in Neck as Vi...,0,NaN,https://www.bloomberg.com/news/articles/2019-1...,all_ads,6
3,[],False,Davidizaverage,NaN,NaN,NaN,[],NaN,NaN,text,...,public,default,73.0,140.0,‘Crushed bodies and shattered bones:’ China’s ...,0,NaN,https://www.washingtonexaminer.com/policy/defe...,all_ads,6
4,[],False,Davidizaverage,NaN,NaN,NaN,[],NaN,NaN,text,...,public,default,73.0,140.0,Economist who slated colleagues’ work is tippe...,0,NaN,https://www.theguardian.com/world/2019/oct/13/...,all_ads,6

# Select Relevant Columns

In [31]:
news.columns

Index(['all_awardings', 'allow_live_comments', 'author', 'author_cakeday',
       'author_flair_background_color', 'author_flair_css_class',
       'author_flair_richtext', 'author_flair_text', 'author_flair_text_color',
       'author_flair_type', 'author_fullname', 'author_patreon_flair',
       'awarders', 'can_mod_post', 'contest_mode', 'created_utc', 'domain',
       'full_link', 'gilded', 'gildings', 'id', 'is_crosspostable', 'is_meta',
       'is_original_content', 'is_reddit_media_domain', 'is_robot_indexable',
       'is_self', 'is_video', 'link_flair_background_color',
       'link_flair_richtext', 'link_flair_text', 'link_flair_text_color',
       'link_flair_type', 'locked', 'media', 'media_embed', 'media_only',
       'no_follow', 'num_comments', 'num_crossposts', 'over_18',
       'parent_whitelist_status', 'permalink', 'pinned', 'post_hint',
       'preview', 'pwls', 'retrieved_on', 'score', 'secure_media',
       'secure_media_embed', 'selftext', 'send_replies', 'spoiler',
       'steward_reports', 'stickied', 'subreddit', 'subreddit_id',
       'subreddit_subscribers', 'subreddit_type', 'thumbnail',
       'thumbnail_height', 'thumbnail_width', 'title', 'total_awards_received',
       'updated_utc', 'url', 'whitelist_status', 'wls'],
      dtype='object')

### Create DataFrames

In [32]:
# Relevant Columns
columns = [
    "subreddit",
    "title",
    "score",
    "num_comments",
    "domain"
]

In [33]:
# Create DataFrames for each subreddit based on relevant columns
news_df = news.loc[:, columns]
world_df = world.loc[:, columns]

# Data Cleaning

In [34]:
news_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 0 to 4999
Data columns (total 5 columns):
subreddit       5000 non-null object
title           5000 non-null object
score           5000 non-null int64
num_comments    5000 non-null int64
domain          5000 non-null object
dtypes: int64(2), object(3)
memory usage: 234.4+ KB

In [35]:
world_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5000 entries, 0 to 4999
Data columns (total 5 columns):
subreddit       5000 non-null object
title           5000 non-null object
score           5000 non-null int64
num_comments    5000 non-null int64
domain          5000 non-null object
dtypes: int64(2), object(3)
memory usage: 234.4+ KB

In [36]:
news_df.describe()

               score  num_comments
count    5000.000000    5000.00000
mean      171.822800      21.20300
std      3554.678513     247.46699
min         0.000000       0.00000
25%         1.000000       0.00000
50%         1.000000       0.00000
75%         1.000000       0.00000
max    195117.000000   10225.00000

In [37]:
world_df.describe()

               score  num_comments
count    5000.000000   5000.000000
mean      404.049600     39.825000
std      4514.615845    307.492293
min         0.000000      0.000000
25%         1.000000      0.000000
50%         1.000000      2.000000
75%        13.000000      7.000000
max    124420.000000   7552.000000

In [38]:
news_domains = news_df["domain"].value_counts().head(15).index

In [39]:
world_domains = world_df["domain"].value_counts().head(15).index

In [40]:
count = 0
for site in news_domains:
    if site in world_domains:
        count +=1
print("Shared Top 15 domains:")
count/len(news_domains)

Shared Top 15 domains:

0.6

Neither dataframe seem to include improper values and should be predictive of future posts within the same subreddit.

### Lemmatizing and Stemming

In [41]:
def title_tokenize(raw_title, style):
    # Function adapted from GA 5.05 NLP I lecture
    
    # Remove non-letters
    letters_only = re.sub("[^a-zA-Z]", " ", raw_title)
    
    # Lower and split words of each title
    words = letters_only.lower().split()
    
    # Search through a set of stopwords
    stops = set(stopwords.words('english'))
    
    # Remove stop words from titles
    meaningful_words = [w for w in words if w not in stops]
    
    if style == "lem":
        # Lemmatize each word
        lemmatizer = WordNetLemmatizer()
        adjusted_root = [lemmatizer.lemmatize(word) for word in meaningful_words]
    elif style == "stem":
        # Stem each word
        stemmer = PorterStemmer()
        adjusted_root = [stemmer.stem(word) for word in meaningful_words]
    else:
        print("Improper entry. Use 'lem' for lemmatizing or 'stem' for stemming.")

    # Rejoin titles
    return(" ".join(adjusted_root))

In [42]:
# Lemmatize News and Worldnews titles
news_df["lem_title"] = [title_tokenize(news_df["title"][i], "lem") for i in news.index]
world_df["lem_title"] = [title_tokenize(world_df["title"][i], "lem") for i in world.index]

In [43]:
# Stem News and Worldnews titles
news_df["stem_title"] = [title_tokenize(news_df["title"][i], "stem") for i in news.index]
world_df["stem_title"] = [title_tokenize(world_df["title"][i], "stem") for i in world.index]

In [44]:
# Concatenate News and Worldnews data
df = pd.concat([news_df, world_df], ignore_index = True)

In [45]:
df.loc[(df["lem_title"] == "") | (df["stem_title"] == "")]

,subreddit,title,score,num_comments,domain,lem_title,stem_title
99,news,بالفيـ ديو رسالة ظافر العابدين اليوم للتونسيين...,1,1,youtube.com,,
148,news,릴게임,1,0,reelsohot.com,,
218,news,زينب زوجة أحمد زكى بالبيه البواب بأحدث ظهور كا...,1,1,youtube.com,,
345,news,ЗАБОЛЕВШИЙ ФУТБОЛИСТ СБОРНОЙ АНГЛИИ ИГРАЛ В ПО...,1,0,livesports.kz,,
374,news,بالفيـ ديو..بعد إعجابه بـ كيم كارداشيان .. أحل...,1,1,youtube.com,,
...,...,...,...,...,...,...,...
9840,worldnews,طائرة الجليد الأسود,1,0,udefense.info,,
9922,worldnews,メルカリで利用制限やアカウント停止ペナルティから復活させる方法,1,1,h9nfp.com,,
9964,worldnews,不是无知本身，而是对无知的无知，才是知识的死亡。,1,1,dailyeng.github.io,,
9965,worldnews,高校生がバイト以外で稼ぐ方法。在宅ワーク可【今すぐお金が欲しい】,1,1,h9nfp.com,,
9968,worldnews,正社員からパートは後悔する？子育てと両立する権利収入を目指せ,1,1,h9nfp.com,,

There exist lemmatized and stemmed titles that are empty strings as they originate from non-english languages. Remove the non-english language rows.

In [46]:
# Set the data equal to all rows that don't contain empty strings
df = df.loc[(df["lem_title"] != "") | (df["stem_title"] != "")]

In [86]:
# Get word frequencies for News subreddit
news = []
mask = df.loc[df["subreddit"] == "news", "lem_title"]
for i in mask:
    for word in i.split():
        news.append(word)

In [87]:
print("News:")
pd.Series(news).value_counts().head(10)

News:

trump     302
u         296
say       222
new       195
n         177
china     163
amp       161
syria     161
news      157
police    152
dtype: int64

In [84]:
# Get word frequencies for Worldnews subreddit
world = []
mask = df.loc[df["subreddit"] == "worldnews", "lem_title"]
for i in mask:
    for word in i.split():
        world.append(word)

In [85]:
print("World:")
pd.Series(world).value_counts().head(10)

World:

u          650
trump      577
syria      562
turkey     438
say        407
hong       395
kong       395
china      356
turkish    239
protest    221
dtype: int64

# Export Data

In [47]:
df.to_csv("../data/combined.csv")